### ISSUE TITLE
NullPointerException.

### ISSUE THREAD

**Issue by yadavvi91** [pashkobohdan/Music-Player#2]
``` java
Caused by: java.lang.NullPointerException
    at controllers.Controller.readPlaylistList(Controller.java:308)
    at controllers.Controller.initialize(Controller.java:139)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
    ... 12 more
```

A `NullPointerException` when running with `Java8` and `JavaFXSceneBuilder2.0`

**Comment by pashkobohdan** [comment]
Sorry for so long ansver. Under what conditions does it play?. When you don't have playlists ?

**Comment by yadavvi91** [comment]
I found out what the problem is - 

1) The playlists **_have_** to be created before we start running the application.
2) The paths are `Windows` specific, so I had to change it to something like this - 

```
-    public static final String PICTURES_PATH = PROJECT_PATH+"\\src\\pictures";
+    public static final String PICTURES_PATH = PROJECT_PATH+"/src/pictures";
```

Could you make it more generic such that it does not crash if there are no playlists. Also could you make the program accept both the `Linux` as well as `Windows` version for paths.

**Comment by pashkobohdan** [comment]
It meant that, at least one playlist must be created before running
Отправлено с помощью BlueMail

На 9:52, 09.03.2016, в 9:52, Vishal Yadav notifications@github.com написал:п>I found out what the problem is -

**Comment by pashkobohdan** [comment]
Thanks

**Comment by pashkobohdan** [comment]
fix it

**Comment by yadavvi91** [comment]
The path error is fixed, however, the playlist is still shown by default.

**Comment by pashkobohdan** [comment]
I fixed this later ( today )

Отправлено с помощью BlueMail

На 7:18, 10.03.2016, в 7:18, Vishal Yadav notifications@github.com написал:п>The path error is fixed, however, the playlist is still shown by

**Comment by pashkobohdan** [comment]
I fixed bug with playlist
